### ISSUE TITLE
error parsing time  "failed" 

### ISSUE THREAD

**Issue by brahimwakrim87** [kubetail-org/kubetail#115]
Hi, 
  i'm havie this problème , 

{"level":"fatal","error":"parsing time \"failed\" as \"2006-01-02T15:04:05.999999999Z07:00\": cannot parse \"failed\" as \"2006\"","time":"2024-10-01T20:33:19.669263972Z"}
![image](https://github.com/user-attachments/assets/0a27e80c-d92b-43f1-b787-cd4538f07ec8)

any one can help!!!!!

**Comment by amorey** [comment]
Thanks for the bug report! It looks like you have a line in your logs that says "failed" where there should be a timestamp. Can you share the log file or some content from the file to help us debug it? Did the error only happen once with one file or is it happening repeatedly?

**Comment by brahimwakrim87** [comment]
Hi,

Thank you for your response.

Could you please let me know where I can find this file, or how to run the server in debug mode?

Best regards,

**Comment by amorey** [comment]
Based on the error, it looks like you have a line in one of your pod logs that reads "failed" instead of the usually formatted line. If that's the case then you can find the problematic pod log using Kubernetes Dashboard.

Are you seeing the Kubetail error consistently? What page are you on in the app when you encounter the error?

**Comment by amorey** [comment]
I modified the behavior so that it skips malformed Kubernetes logging messages rather than throwing a fatal error. If you upgrade using helm chart version 0.7.3 it should fix the problem:

```console
helm repo update
helm upgrade kubetail kubetail/kubetail --namespace kubetail
```

Let me know if you run into this issue again or if you run into any other problems.

**Comment by brahimwakrim87** [comment]
Great, it worked, thank you very much.

> I modified the behavior so that Kubetail skips malformed Kubernetes logging messages rather than throwing a fatal error. If you upgrade using helm chart version 0.7.3 it should fix the problem:
> 
> ```
> helm repo update
> helm upgrade kubetail kubetail/kubetail --namespace kubetail
> ```
> 
> Let me know if you run into this issue again or if you run into any other problems.

Great, it worked, thank you very much.
