### ISSUE TITLE
Chrome hangs loading logs

### ISSUE THREAD

**Issue by nodesocket** [kubetail-org/kubetail#2]

**Comment by amorey** [comment]
Does it hang when you view the demo site with the same browser? https://www.kubetail.com/demo

It's probably hanging because the collection of log files you're looking at have a lot of data and the frontend is having trouble processing it. Improving support for large files is #1 on the todo list.

**Comment by nodesocket** [comment]
Not sure how much log data. Is there a way I can get that using `kubectl`? Demo works fine.

**Comment by amorey** [comment]
Great, thanks for checking. If the demo is fine with the browser then it's an issue with the amount of data. Unfortunately the only way to check the size of a log with kubectl is to download the entire file (this is part of the reason why it's a non-trivial problem to fix on the frontend):
```
kubectl logs -n [namespace] [pod-name] | wc -l 
```

**Comment by nodesocket** [comment]
Honestly that much data. I guess PostgreSQL kinda has a bit with 3.5k but....

```shell
$ kubectl logs -n macd pricesd-75b8bcf79c-gfzcd | wc -l
265
$ kubectl logs -n macd pg-0 | wc -l
3529
$ kubectl logs -n macd metabase-854cb558cd-d97l7 | wc -l
5963
```

**Comment by amorey** [comment]
Kubetail merges all data into a single stream and adds each line as a row to a `<table>` so the browser is hanging dealing with ~10K table rows with 8 cells each. That's around where I've seen problems in other contexts so it isn't too surprising.

**Comment by amorey** [comment]
At the API level yes but it isn't currently enabled in the frontend. In the mean time I can configure the frontend to only stream new data by default - would this be helpful for you?

**Comment by nefarius** [comment]
My bold claim would be that most users would expect it to behave like tail and by default only start streaming from e.g. the past 10 or so elements form each container into the past, that should do it as a quick fix IMHO.

**Comment by nodesocket** [comment]
> My bold claim would be that most users would expect it to behave like tail and by default only start streaming from e.g. the past 10 or so elements form each container into the past, that should do it as a quick fix IMHO.

That makes sense by default you start from when opened streaming (live). Would be awesome to have a way to select last hour or last 24 hours with a select dropdown or something. Thanks 🙏

**Comment by amorey** [comment]
> That makes sense by default you start from when opened streaming (live). Would be awesome to have a way to select last hour or last 24 hours with a select dropdown or something. Thanks 🙏

That's the plan!

**Comment by nefarius** [comment]
Slight switch of arguments 👇 

```bash
helm repo update kubetail
```

**Comment by nefarius** [comment]
> Thanks again for your help and let me know if you have any suggestions!

Thanks for the quick fix, I just deployed and it works as expected! (now all we need is ANSI color support hehe)

**Comment by amorey** [comment]
@nefarius Thanks for the heads up about the helm command! I fixed it in the original comment.

**Comment by amorey** [comment]
@nefarius @nodesocket @KyteProject I just published a new release candidate (0.4.0-rc2) that addresses this issue at a deeper level by using virtualization so only the records in the view window are rendered in the DOM. Here's the new code running on the demo site:
https://www.kubetail.com/demo

To try it out on your cluster you can cherry pick the `0.4.0-rc2` tag (don't forget to use `--reset-values` to revert later):
```
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail --set image.tag=0.4.0-rc2
```

There are still some bugs to fix before it can be merged into the trunk but the new code makes some modifications to the behavior (e.g. introduces "Jump to start", "Jump to end", "Jump to time" buttons) so it would be useful to get some feedback on that as well to make sure we're headed in the right direction.

**Comment by nefarius** [comment]
I just updated and will let it run for a while 👍

**Comment by nefarius** [comment]
> There are still some bugs to fix before it can be merged into the trunk but the new code makes some modifications to the behavior (e.g. introduces "Jump to start", "Jump to end", "Jump to time" buttons) so it would be useful to get some feedback on that as well to make sure we're headed in the right direction.

IDK if that is already on your radar (probably is) but I noticed that the auto-scroll-to-bottom (whatever the right term) feature rather quickly and regularly fails to do its job and the scrolling simply stops.

**Comment by amorey** [comment]
Thanks, I'll work on that. The other known issues are:
* New pods aren't getting tailed
* Pressing "pause" then "play" will load events as they are streamed in rather than ordered by timestamp

Let me know any other issues you see big & small. I hope the test is going well!

**Comment by amorey** [comment]
I just pushed a new version (0.4.0-rc3) that fixes the bugs mentioned previously:
- Autoscroll is working more reliably (though I've seen it shut off occasionally so there's still more work to do)
- New pods will get tailed automatically
- Pressing "play" after being "pause" will order missing events by timestamp then start streaming

```
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail --set image.tag=0.4.0-rc3
```

It's running live here:
https://www.kubetail.com/demo

Let me know if you notice any other bugs big or small!

**Comment by amorey** [comment]
Quick update - latest version is now 0.4.0-rc4:
```
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail --set image.tag=0.4.0-rc4
```
https://www.kubetail.com/demo

**Comment by amorey** [comment]
Quick update - latest version is now 0.4.0-rc5:

```sh
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail --set image.tag=0.4.0-rc5
```

https://www.kubetail.com/demo

Please check it out and let me know if you notice any bugs. I think this release candidate reaches feature parity with the current stable version so unless there are any issues, I'll merge with the main branch and publish a new stable version soon.

**Comment by nodesocket** [comment]
I just upgraded to `0.4.0`. We report any issues. Thanks 👍🏻

**Comment by nodesocket** [comment]
@amorey getting a JS error with `0.4.0`:

![Screenshot 2024-03-20 at 2 30 55 AM](https://github.com/kubetail-org/kubetail/assets/523312/f0b6229b-9a31-4e05-9c39-f16716132ffa)

**Comment by amorey** [comment]
Thanks for the screenshot. Did you get the bug on initial load? Do you see the bug with all your logs or just some? Any other details you can provide would be very helpful.

**Comment by nodesocket** [comment]
@amorey that seemed to fix it. Thanks!
