### ISSUE TITLE
Name of the session cookie

### ISSUE THREAD

**Issue by jkroepke** [kubetail-org/kubetail#22]
Hi,

is it possible to change the name of the cookie? I would like to use cookie prefixes.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes

**Comment by amorey** [comment]
I pushed a new version (0.1.9) that makes the session cookie name configurable via the `session.cookie.name` config option. I also updated the helm chart so if you add it to your values.yaml file under `config`, it should work. Let me know if you run into any problems!
