### ISSUE TITLE
[kubetail] Run kubetail under a subpath (behind reverse proxy)

### ISSUE THREAD

**Issue by jkroepke** [kubetail-org/kubetail#24]
HI,

I currently plan to run kubetali as part of some operational toolset, together with other tooling.
The toolset shared one domains and each application has a sub-path.

Would it be possible to add an config option to allow kubetail running on a sub-path?

**Comment by amorey** [comment]
Sure, that's a good suggestion. It already runs under the sub-path "/proxy/" to support `kubectl proxy` so it shouldn't be too difficult to make this configurable. I can take a look.

**Comment by amorey** [comment]
Here's a PR that implements this: https://github.com/kubetail-org/kubetail/pull/28. Once merged you'll be able to deploy kubetail on a sub-path by using the `base-path` config variable (default: "/"):

```yaml
base-path: /my-sub-path
```

Let me know if you have any suggestions.

**Comment by jkroepke** [comment]
That looks good to me, thanks!
