### ISSUE TITLE
GraphQL WebSocket connections not working on Chromium Edge on Windows 10

### ISSUE THREAD

**Issue by nefarius** [kubetail-org/kubetail#3]

**Comment by amorey** [comment]
I have a PR that should fix this https://github.com/kubetail-org/kubetail/pull/5

Can you try out the kubetail/kubetail@0.1.9-rc2 helm chart? This should work:
```
helm upgrade kubetail kubetail/kubetail --namespace kubetail --version 0.1.9-rc2
```

**Comment by nefarius** [comment]
Does this need some time to work?

```
Error: chart "kubetail" matching 0.1.9-rc2 not found in kubetail index. (try 'helm repo update'): no chart version found for kubetail-0.1.9-rc2
```

**Comment by nefarius** [comment]
Hey hey! 🎉 

![image](https://github.com/kubetail-org/kubetail/assets/286631/0c5d94c0-3e1c-44d1-8c50-e5db1d9e62eb)

**Comment by amorey** [comment]
Nice!!! Thanks for testing it out. The PR changes the way that kubetail protects against cross-site WebSocket connection requests so I want to tread carefully and double check the code before publishing a new release. Will try to get it out asap. If you have some time, it'd be useful to get another set of eyes on this: https://github.com/kubetail-org/kubetail/pull/5. I'm using a cookie with `SameSite=Strict` to ensure that only same-site connections are allowed.

**Comment by nefarius** [comment]
Not sure how valuable my input is here, I see what you're trying to achieve here, however I am not well versed enough in Go and front-end development to make a fair judgment.

**Comment by amorey** [comment]
The fix is live in kubetail:0.1.3 (chart v0.1.9):
```
helm update repo kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail --version 0.1.9
```

I changed the strategy from using a `SameSite=Strict` cookie to using CSRF token validation which is more secure. Let me know if you notice any issues.

**Comment by nefarius** [comment]
Just updated, everything is working 👍

**Comment by amorey** [comment]
Nice! Thanks again for your help debugging the problem.
