### ISSUE TITLE
Feature Request: wrap messages so scrolling right is not necessary

### ISSUE THREAD

**Issue by krzwiatrzyk** [kubetail-org/kubetail#7]

**Comment by amorey** [comment]
Makes sense. Will take a look.

**Comment by amorey** [comment]
I just published a new version (0.1.5) that adds a "Wrap" option to the settings dropdown in the top-right corner that implements this:
![Kubetail___Log_Viewer_and_Feature_Request__wrap_messages_so_scrolling_right_is_not_necessary_·_Issue__7_·_kubetail-org_kubetail](https://github.com/kubetail-org/kubetail/assets/75881/253e6fa3-3638-403b-9f3d-d5b2640b4afe)

Currently, this option will reset every time you load a new console but I hope to address this soon.

**Comment by krzwiatrzyk** [comment]
Awesome, I will surely check it out, thanks for letting me now

**Comment by amorey** [comment]
Quick update - I pushed a new stable version (0.4.0) based on the last rc. Here's the command to upgrade (using `--reset-values` to clear out previous use of `--set`):

```sh
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail --reset-values
```
