### ISSUE TITLE
Error when adding additional sources

### ISSUE THREAD

**Issue by The-Judge** [kubetail-org/kubetail#95]
Hi everyone,

this even occurs in the demo instance at [https://www.kubetail.com/demo](https://www.kubetail.com/demo):

When clicking the blue "+" icon in the left menu next to "Sources" and select any additional source, this results in an error message:

```
Oops!
Sorry, an unexpected error has occurred.

not implemented:
```

**Comment by amorey** [comment]
Thanks for the heads up! It's fixed in the latest version (0.6.2). Here's the helm command to upgrade:

```console
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail
```
